# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gradeup
tagline:          'Study more, score better'
description:      'Gradeup Engineering Blog'
url:              gradeup.github.io
baseurl:          /

author:
  name:           'Gradeup Dev'
  url:            mailto:developer@gradeup.co

paginate:         5
paginate_path: "page:num"

github:
  repo:           https://github.com/gradeup/gradeup.github.io

gems: [jekyll-paginate]
